//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Solution1.Module.BusinessObjects.uniDB
{

    public partial class address : XPBaseObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string fcity;
        public string city
        {
            get { return fcity; }
            set { SetPropertyValue<string>(nameof(city), ref fcity, value); }
        }
        string fstreet;
        public string street
        {
            get { return fstreet; }
            set { SetPropertyValue<string>(nameof(street), ref fstreet, value); }
        }
        string fregion;
        public string region
        {
            get { return fregion; }
            set { SetPropertyValue<string>(nameof(region), ref fregion, value); }
        }
        string fpostalCode;
        public string postalCode
        {
            get { return fpostalCode; }
            set { SetPropertyValue<string>(nameof(postalCode), ref fpostalCode, value); }
        }
        [PersistentAlias("[city] + ', ' + [region] + ', ' + [street]")]
        public string fullAddress
        {
            get { return (string)(EvaluateAlias(nameof(fullAddress))); }
        }
    }

}
