//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Solution1.Module.BusinessObjects.uniDB
{

    public partial class Instructor : XPBaseObject
    {
        int fcode;
        [Key(true)]
        public int code
        {
            get { return fcode; }
            set { SetPropertyValue<int>(nameof(code), ref fcode, value); }
        }
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        address faddress;
        public address address
        {
            get { return faddress; }
            set { SetPropertyValue<address>(nameof(address), ref faddress, value); }
        }
        DateTime fDOB;
        public DateTime DOB
        {
            get { return fDOB; }
            set { SetPropertyValue<DateTime>(nameof(DOB), ref fDOB, value); }
        }
        [Association(@"courseReferencesInstructor")]
        public XPCollection<course> courses { get { return GetCollection<course>(nameof(courses)); } }
        [Association(@"phoneReferencesInstructor")]
        public XPCollection<phone> phones { get { return GetCollection<phone>(nameof(phones)); } }
    }

}
