//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Solution1.Module.BusinessObjects.uniDB
{

    public partial class student : XPBaseObject
    {
        int fcode;
        [Key]
        public int code
        {
            get { return fcode; }
            set { SetPropertyValue<int>(nameof(code), ref fcode, value); }
        }
        string fname;
        [DevExpress.ExpressApp.Model.Required]
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        address faddress;
        public address address
        {
            get { return faddress; }
            set { SetPropertyValue<address>(nameof(address), ref faddress, value); }
        }
        DateTime fDOB;
        public DateTime DOB
        {
            get { return fDOB; }
            set { SetPropertyValue<DateTime>(nameof(DOB), ref fDOB, value); }
        }
        major fmajor;
        public major major
        {
            get { return fmajor; }
            set { SetPropertyValue<major>(nameof(major), ref fmajor, value); }
        }
        string fschool;
        public string school
        {
            get { return fschool; }
            set { SetPropertyValue<string>(nameof(school), ref fschool, value); }
        }
        [Association(@"studnetCoursesReferencesstudent")]
        public XPCollection<studnetCourses> studnetCoursesCollection { get { return GetCollection<studnetCourses>(nameof(studnetCoursesCollection)); } }
        [Association(@"phoneReferencesstudent")]
        public XPCollection<phone> phones { get { return GetCollection<phone>(nameof(phones)); } }
    }

}
