//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Solution1.Module.BusinessObjects.uniDB
{

    public partial class TA : XPBaseObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        string fDOB;
        public string DOB
        {
            get { return fDOB; }
            set { SetPropertyValue<string>(nameof(DOB), ref fDOB, value); }
        }
        address faddress;
        public address address
        {
            get { return faddress; }
            set { SetPropertyValue<address>(nameof(address), ref faddress, value); }
        }
        [Association(@"phoneReferencesTA")]
        public XPCollection<phone> phones { get { return GetCollection<phone>(nameof(phones)); } }
        [Association(@"courseTAsReferencesTA"), Aggregated]
        public XPCollection<courseTAs> courseTAsCollection { get { return GetCollection<courseTAs>(nameof(courseTAsCollection)); } }
    }

}
